id: A3C193895
title: Toh_163-Questions_of_Ratnaj%C4%81lin-v2
type: translation
pechas:
- I4A7797D4
- I381EC883
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-059-006
  eft-text-version: 1.0.1 2020
  title: Toh_163-Questions_of_Ratnaj%C4%81lin-v2
alignment_to_base:
  I4A7797D4/444F: C2B0
  I381EC883/CCAC: C2B0
